### ISSUE TITLE
python3 issue serving images

### ISSUE THREAD

**Issue by zimeon** [zimeon/iiif#15]
New merge for 0.6.1 (#14) has problems with iiif_testserver.py on python3. Even with the very latest Flask and dependencies, there is a problem with utf-8 confusion wrt images data:

```
(py3)simeon@RottenApple iiif>./iiif_testserver.py --debug
Installing pil IIIFManipulator at /1.0_pil/ v1.0 none
Installing pil IIIFManipulator at /1.1_pil/ v1.1 none
Installing pil IIIFManipulator at /2.0_pil/ v2.0 none
Starting test server on http://localhost:8000/ ...
...
IIIFHandler: image_request: starfish
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/Users/simeon/miniconda3/envs/py3/lib/python3.5/site-packages/werkzeug/wsgi.py", line 761, in __next__
    data = self.file.read(self.buffer_size)
  File "/Users/simeon/miniconda3/envs/py3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
werkzeug: 127.0.0.1 - - [22/Apr/2016 13:16:06] "GET /2.0_pil/starfish/full/256,256/0/default HTTP/1.1" 200 -
```

**Comment by zimeon** [comment]
Change seems good. Done.
